-- 코드를 입력하세요
SELECT YEAR(s.SALES_DATE) AS YEAR, 
       MONTH(s.SALES_DATE) AS MONTH, 
       u.GENDER, 
       COUNT(DISTINCT s.USER_ID) AS USERS
FROM USER_INFO u
JOIN ONLINE_SALE s ON u.USER_ID = s.USER_ID
WHERE u.GENDER IS NOT NULL
GROUP BY DATE_FORMAT(s.SALES_DATE, '%Y-%m'), u.GENDER
ORDER BY YEAR(s.SALES_DATE) ASC, MONTH(s.SALES_DATE) ASC, u.GENDER ASC

# SELECT * FROM ONLINE_SALE;