-- 코드를 입력하세요
WITH RECURSIVE TIME_TABLE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIME_TABLE WHERE HOUR < 23)

SELECT t.HOUR AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS a
RIGHT JOIN TIME_TABLE t ON HOUR(a.DATETIME) = t.HOUR
GROUP BY HOUR
ORDER BY HOUR ASC;